### ISSUE TITLE
Letters not rendering - showing boxes instead

### ISSUE THREAD

**Issue by peoplecount** [avojak/warble#21]
![screenshot_20220201_133322](https://user-images.githubusercontent.com/6228901/151932407-95895d38-7fed-48d1-9aff-515f6dd5a0ce.png)
sercontent.com/6228901/151932317-638ecb81-7be2-4716-ab74-3f79d01abf3c.png)

On Kubuntu 20.04 (fully updated) installed using flatpak. Updated to 1.2.0 as suggested in OMG Ubuntu thread (https://www.omgubuntu.co.uk/2022/01/warble-wordle-game-clone-for-elementary-os).

**Comment by avojak** [comment]
Thanks for reporting this! My initial assumption is that this is due to the application explicitly using the Inter typeface. I'll have to look into a better way to handle this. I didn't necessarily want to use whatever the current system font is, because by specifying a typeface I can ensure that it works well and appears as intended. I also assumed that Inter was included in the elementary OS runtime, but that must not be the case. Will have to look into this a bit more.

**Comment by peoplecount** [comment]
Thanks. Does this mean that if i install the inter font it should work for
me?

Regards
Bala

**Comment by avojak** [comment]
I _think_ so, but there may be some other issue I'm not aware of. If it does work that would be very helpful for me to know!

**Comment by peoplecount** [comment]
I downloaded the inter font family from [here](https://www.cufonfonts.com/font/inter). It was the first hit from a search. Installing the fonts and restarting warble worked. I am able to play a game. Thanks for the quick support.

**Comment by avojak** [comment]
Awesome - glad that worked! I'm going to still leave this issue open until I can find a better way to handle this so that users on other platforms don't need to download the font themselves.

**Comment by avojak** [comment]
I'm not able to reproduce this issue. Even though Inter isn't available on a clean installation of Kubuntu, it does fallback to a sans serif font:
<img width="1136" alt="Screen Shot 2022-03-19 at 2 10 02 PM" src="https://user-images.githubusercontent.com/3663899/159136902-ead71958-9943-4c2a-b930-ef61f3353977.png">
