### ISSUE TITLE
Titlebar doesn't respect close button position

### ISSUE THREAD

**Issue by cassidyjames** [avojak/warble#36]
I know this app is made for elementary OS, but considering it's on Flathub, it might be nice to be a little more cross-desktop friendly. :wink: Right now, the close button always appears on the left, but most other desktops have it set to the right (GNOME on Fedora, Ubuntu, Pop!_OS, etc.).

I believe this should be pretty easy to respect, as it should be built-in behavior in titlebars; if I get a minute, I can throw a PR your way as well. :smile:

**Comment by avojak** [comment]
Yea this would be a good thing to do for sure! I wonder if this is related to how I manually specified the header bar layout to hide the maximize/restore button? (Window resizing is a whole other issue that needs to be addressed 🤣)

And honestly I can probably drop the forced elementary stylesheet as well to make it fit better on other desktops. The only thing that might need tweaking there is the header on dialogs (I think I saw them appear when testing on other desktops before I forced the elementary style).

**Comment by cassidyjames** [comment]
@avojak the style I don't mind as your app should look how you want, but the window control position would be nice. Note that hiding the maximize button alone doesn't prevent it from being maximized (e.g. with gestures, a dock, window manager menu, etc.) but I think disabling resizability as you've done disables maximizing. So _I think_ you'd be fine with just that.

**Comment by avojak** [comment]
@cassidyjames Looks like the "real" fix is a bit more involved since I'm using libhandy widgets right now. I'd like to circle back on my apps to update them to GTK4 but that probably won't be any time real soon. At that point since libhandy wouldn't be in the picture anymore, I *think* a GTK header bar is supposed to get the hint to not show the maximize/minimize buttons when the application window isn't resizable.

If you're aware of a better interim solution I'd gladly hear it!
